config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.conf.urls.i18n import i18n_patterns
from ajax_select import urls as ajax_select_urls


#
# blog_urls = ([
#     url(r'^', include('zinnia.urls.capabilities')),
#     url(r'^search/', include('zinnia.urls.search')),
#     url(r'^sitemap/', include('zinnia.urls.sitemap')),
#     url(r'^trackback/', include('zinnia.urls.trackback')),
#     url(r'^blog/tags/', include('zinnia.urls.tags')),
#     url(r'^blog/feeds/', include('zinnia.urls.feeds')),
#     url(r'^blog/random/', include('zinnia.urls.random')),
#     url(r'^blog/authors/', include('zinnia.urls.authors')),
#     url(r'^blog/categories/', include('zinnia.urls.categories')),
#     url(r'^blog/comments/', include('zinnia.urls.comments')),
#     url(r'^blog/', include('zinnia.urls.entries')),
#     url(r'^blog/', include('zinnia.urls.archives')),
#     url(r'^blog/', include('zinnia.urls.shortlink')),
#     url(r'^blog/', include('zinnia.urls.quick_entry'))
# ], 'zinnia')
#



urlpatterns = i18n_patterns(
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # User management
    url(r'^select2/', include('django_select2.urls')),
    url(r'^ajax_select/', include(ajax_select_urls)),
    url(r'^', include('coworker.main.urls', namespace='main')),
    # url(r'^(?P<country>[\w-]+)/', include('coworker.place.urls', namespace='place')),
    url(r'^profile/', include('coworker.users.urls', namespace='users')),

    url(r'^accounts/', include('allauth.urls')),

    url(r'^places/', include('coworker.place.urls', namespace='place')),
    url(r'^events/', include('coworker.events.urls', namespace='events')),
    url(r'^services/', include('coworker.services.urls', namespace='services')),
    # url(r'^', include(blog_urls)),
    url(r'^lab/', include('coworker.lab.urls', namespace='lab')),
    url(r'^search/', include('coworker.search.urls', namespace='search')),
    url(r'^social/', include('coworker.social.urls', namespace='social')),


    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^comments/', include('django_comments.urls')),
    # Your stuff: custom urls includes go here


) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        url(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

coworker/lab/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^$', views.ArticleListView.as_view(), name='index'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        views.EntryDetail.as_view(),
        name='entry_detail'),
]

coworker/main/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^$', view=views.Index.as_view(), name='index'),
    url(r'^search/$', view=views.SearchView.as_view(), name='search'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^cities/$', TemplateView.as_view(template_name='pages/cities.html'), name='cities'),
    url(r'^team/$', TemplateView.as_view(template_name='pages/team.html'), name='team'),
    url(r'^contact/$', TemplateView.as_view(template_name='pages/contact.html'), name='contact'),
    url(r'^reviews/$', TemplateView.as_view(template_name='pages/reviews.html'), name='reviews'),
    url(r'^terms/$', TemplateView.as_view(template_name='pages/terms.html'), name='terms'),
    url(r'^privacy-policy/$', TemplateView.as_view(template_name='pages/privacy-policy.html'), name='privacy-policy'),
    url(r'^help/$', TemplateView.as_view(template_name='pages/help.html'), name='help'),
]

coworker/place/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^card/api/(?P<pk>\d+)/$', view=views.PlaceDetailApiView.as_view(), name='detail_card'),
    url(r'^map/api/$', view=views.PlaceMapApiView.as_view(), name='map_api'),


    #url(r'^list-space/success/$', view=views.PlaceAddSuccess.as_view(), name='list-space-success'),


    #photo edit urls


    url(r'^search/autocomplete/$', views.autocomplete),

    url(r'^search/$', view=views.SearchList.as_view(), name='search'),
    url(r'^search/(?P<country>[\w-]+)/', view=views.SearchList.as_view(), name='search-country'), #HERE REMOVED $


    url(r'^(?P<country>[\w-]+)/$', view=views.PlaceCountryList.as_view(), name='country'),
    url(r'^(?P<country>[\w-]+)/(?P<city>[\w-]+)/$', view=views.PlaceCityList.as_view(), name='city'),
    url(r'^(?P<country>[\w-]+)/(?P<city>[\w-]+)/(?P<place>[\w-]+)/$',
        view=views.PlaceView.as_view(), name='place'),
    # url(r'^(?P<city>[\w-]+)/(?P<place>.*)/$', view=views.Place.as_view(), name='place'),


]

coworker/search/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # url(
    #     regex=r'^api/list$',
    #     view=views.EventSearchView.as_view(),
    #     name='search-api'
    # ),
    url(
        # regex=r'^api/autocomplete/(?P<app>[\w-]+)/(?P<model>[\w-]+)',
        regex=r'^api/autocomplete/',
        view=views.Autocomplete.as_view(),
        name='search_autocomplete'
    ),
]

coworker/users/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    # url(regex=r'^$', view=views.UserListView.as_view(), name='list'),
    # url(regex=r'^~redirect/$', view=views.UserRedirectView.as_view(), name='redirect'),
    # url(regex=r'^(?P<username>[\w.@+-]+)/$', view=views.UserDetailView.as_view(), name='detail'),

    #url(regex=r'^~update/$', view=views.UserUpdateView.as_view(), name='update'),
    url(regex=r'^usertype/$', view=views.UserUpdateView.as_view(), name='user_type'),

    url(regex=r'^update_aboutme/$', view=views.UserUpdateView.as_view(), name='update_aboutme'),

    # url(regex=r'^myreviews/$', view=views.UserUpdateView.as_view(), name='myreviews'),
    url(regex=r'^editprofile/$', view=views.UserUpdateView.as_view(), name='editprofile'),
    url(regex=r'^editprofile/$', view=views.UserUpdateView.as_view(), name='editprofile'),

    # url(r'^$', view=views.UserProfileView.as_view(), name='profile'),
    url(r'^$', view=views.UserUpdateView.as_view(), name='profile'),

    url(r'^myreviews/$', view=TemplateView.as_view(template_name='pages/reviews.html'), name='myreviews'),

    url(r'^get_spaces/$', view=TemplateView.as_view(template_name='pages/reviews.html'), name='get_spaces'),
    url(r'^photo/$', view=views.UpdateProfileImage.as_view(), name='photo'),

    url(r'^registration/$', views.registration, name='registration'),
]

coworker/main/models.py
from django.db import models

coworker/search/models.py
from django.db import models

# Create your models here.

coworker/social/models.py
from django.db import models
from django.utils import timezone

from coworker.users.models import User


class Tweet(models.Model):
    user = models.ForeignKey(User, related_name='tweets')
    created = models.DateTimeField(default=timezone.now)
    body = models.TextField()

coworker/social/forms.py
from .models import Tweet
from django import forms


class TweetForm(forms.ModelForm):

    class Meta:
        model = Tweet
        fields = ['body']

coworker/events/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DetailView, ListView, TemplateView
from django.views.decorators.csrf import csrf_exempt
from rest_framework.response import Response

from config.es_client import es_client

from rest_framework_elasticsearch import es_views, es_pagination, es_filters
# from .search_indexes import EventIndex
# from .search import bulk_indexing

from core.mixins import SearchBase
from coworker.events.models import Event


class SearchList(SearchBase, TemplateView):
    template_name = 'events/search_events.html'

    # def get(self, request, *args, **kwargs):
    #     return render(request, self.template_name, ctx)
    #
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['object_list'] = Event.objects.all()
        return ctx


class EventDetailView(DetailView):
    model = Event
    template_name = 'events/event_detail.html'
    slug_url_kwarg = "event"

    def get_context_data(self, **kwargs):
        return super(EventDetailView, self).get_context_data(**kwargs)



class AutocompleteBase:
    pass
from django.contrib.postgres.search import SearchVector

class AutocompleteEvent(AutocompleteBase, View):
    def get(self, request, *args, **kwargs):
        ctx = {}
        q = request.GET["q"]
        # from django.contrib.postgres.search import TrigramSimilarity
        # Event.objects.annotate(similarity=TrigramSimilarity('name', q)).filter(similarity__gt=0.3).order_by('-similarity')
        from .documents import EventDocument

        ss = EventDocument.search().query("match", description=q)
        qs = ss.to_queryset()
        # qs is just a django queryset and it is called with order_by to keep
        # the same order as the elasticsearch result.

        for event in ss:
            print(event.name, event.description)

        # ctx['q'] = list(Event.objects.filter(name__search=q).values_list("name", flat=True))
        # import pdb; pdb.set_trace()
        # return JsonResponse(ctx)
        return JsonResponse({"5162-coworkchm":{"value":"Cowork CHM, Hong Kong, Hong Kong","label":"Cowork CHM, Hong Kong, Hong Kong","loc":"3","idx":"5162","coworkspace_url":"hong-kong\/hong-kong\/cowork-chm"},"1807-coworkingspacebytheventures":{"value":"Coworking Space by TheVentures, Ho Chi Minh City, Vietnam","label":"Coworking Space by TheVentures, Ho Chi Minh City, Vietnam","loc":"3","idx":"1807","coworkspace_url":"vietnam\/ho-chi-minh-city\/coworking-space-by-theventures"},"2309-coworkinglegian":{"value":"Coworking Legian, Bali, Indonesia","label":"Coworking Legian, Bali, Indonesia","loc":"3","idx":"2309","coworkspace_url":"indonesia\/bali\/coworking-legian"},"1101-coworkzonehiteccity":{"value":"CoworkZone Hitec City, Hyderabad, India","label":"CoworkZone Hitec City, Hyderabad, India","loc":"3","idx":"1101","coworkspace_url":"india\/hyderabad\/coworkzone-hitec-city"},"4414-coworkinghub":{"value":"Coworking Hub, Hyderabad, India","label":"Coworking Hub, Hyderabad, India","loc":"3","idx":"4414","coworkspace_url":"india\/hyderabad\/coworking-hub"},"5274-coworking24":{"value":"CO-WORKING 24, Hyderabad, India","label":"CO-WORKING 24, Hyderabad, India","loc":"3","idx":"5274","coworkspace_url":"india\/hyderabad\/co-working-24"},"2088-coworkingurquiza":{"value":"Coworking Urquiza, Buenos Aires, Argentina","label":"Coworking Urquiza, Buenos Aires, Argentina","loc":"3","idx":"2088","coworkspace_url":"argentina\/buenos-aires\/coworking-urquiza"},"49-coworkingrosario":{"value":"Coworking Rosario, Rosario, Argentina","label":"Coworking Rosario, Rosario, Argentina","loc":"3","idx":"49","coworkspace_url":"argentina\/rosario\/coworking-rosario"},"v_s":{"value":"cowor","label":"<span>View All Results<\/span>","loc":0,"idx":0,"coworkspace_url":""}})

    def post(self, request, *args, **kwargs):
        return JsonResponse({"170-":{"value":"Moscow, Russia","label":"Moscow, Russia","loc":"2","idx":"170","coworkspace_url": "null"},"1489-cow":{"value":"Co.W, Salem, United States","label":"Co.W, Salem, United States","loc":"3","idx":"1489","coworkspace_url":"united-states\/oregon\/salem\/cow"},"5162-coworkchm":{"value":"Cowork CHM, Hong Kong, Hong Kong","label":"Cowork CHM, Hong Kong, Hong Kong","loc":"3","idx":"5162","coworkspace_url":"hong-kong\/hong-kong\/cowork-chm"},"1807-coworkingspacebytheventures":{"value":"Coworking Space by TheVentures, Ho Chi Minh City, Vietnam","label":"Coworking Space by TheVentures, Ho Chi Minh City, Vietnam","loc":"3","idx":"1807","coworkspace_url":"vietnam\/ho-chi-minh-city\/coworking-space-by-theventures"},"2309-coworkinglegian":{"value":"Coworking Legian, Bali, Indonesia","label":"Coworking Legian, Bali, Indonesia","loc":"3","idx":"2309","coworkspace_url":"indonesia\/bali\/coworking-legian"},"792-cowerkz":{"value":"CoWerkz, Singapore, Singapore","label":"CoWerkz, Singapore, Singapore","loc":"3","idx":"792","coworkspace_url":"singapore\/singapore\/cowerkz"},"1101-coworkzonehiteccity":{"value":"CoworkZone Hitec City, Hyderabad, India","label":"CoworkZone Hitec City, Hyderabad, India","loc":"3","idx":"1101","coworkspace_url":"india\/hyderabad\/coworkzone-hitec-city"},"4414-coworkinghub":{"value":"Coworking Hub, Hyderabad, India","label":"Coworking Hub, Hyderabad, India","loc":"3","idx":"4414","coworkspace_url":"india\/hyderabad\/coworking-hub"},"v_s":{"value":"cow","label":"<span>View All Results<\/span>","loc":0,"idx":0,"coworkspace_url":""}})

coworker/lab/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, TemplateView, CreateView, FormView
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, TemplateView, CreateView, FormView
from django.views import View
from .models import Entry
# Create your views here.
# aricles


class ArticleListView(View):
    template_name = "lab/lab_index.html"

    def get(self, request, *args, **kwargs):
        ctx = {}
        ctx['articles'] = Entry.objects.all()
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        #TODO figure out why and where called post method
        return self.get(request, *args, **kwargs)



class EntryDetail(DetailView):
    template_name = "lab/entry_detail.html"
    model = Entry
    context_object_name = "article"
# class ArticleListView(Views):
#     model = Entry
#     context_object_name = "articles"
#     template_name = "lab/lab_index.html"
#

coworker/main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView
from coworker.place.models import Place, Category
from coworker.services.models import Category as ServiceCategory, Service
from coworker.users.models import User



class Index(TemplateView):
    template_name = 'responsive/index.html'

    def get_context_data(self, **kwargs):
        # places_tmp = Place.objects.order_by('?').all()[:8]
        # d = {}
        # for i, p in enumerate(places_tmp):
        #     d["place_%s" % (i+1)] = p
        # ctx = {
        #     "places": Place.objects.order_by('?').all()[:10],
        # }
        # ctx['place_category'] = list(Category.objects.values_list('name', flat=True))
        # ctx['service_categories'] = list(ServiceCategory.objects.values_list('name', flat=True))
        # event_category = Category.objects.all()
        # search_category = Category.objects.all()
        ctx = {}
        return ctx

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('main:search'))
        return super().get(request, *args, **kwargs)


from coworker.search.backends import get_search_backend


class SearchView(View):
    template_name = 'responsive/places.html'
    # template_name = 'pages/map_tab.html'
    search_key = "q"
    search_backend = 'default'

    def get(self, request, *args, **kwargs):
        ctx = {}
        q = request.GET.get(self.search_key)
        ctx['q'] = q if q != 'None' else ''
        page = request.GET.get("f", "map")

        if page == "map":
            self.template_name = 'responsive/map_tab.html'
        elif page in ["places", "top", "latest"]:
            backend = get_search_backend(self.search_backend)
            places = Place.objects.all()
            if q:
                places = backend.search(q, model_or_queryset=places)
            else:
                places = Place.objects.order_by("?")[:10]
            ctx["object_list"] = places
        elif page == "investors":
            ctx["object_list"] = User.objects.filter(user_type=User.INVESTORS)

        return render(request, self.template_name, ctx)

coworker/templates/responsive/base.html
{% load static %}
{% load i18n %}
{% load auth_forms %}
{% load sekizai_tags %}


<!DOCTYPE html>
<!-- saved from url=(0055)# -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">


    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" type="text/css">
    <title>{% block title %}{% trans "Spacesmap. It's what's happening." %}{% endblock %}</title>
    <meta name="description" content="From breaking news and entertainment to sports and politics, get the full story with all the live commentary.">

    {#    <meta name="msapplication-TileImage" content="//abs.twimg.com/favicons/win8-tile-144.png">#}
    <meta name="msapplication-TileColor" content="#00aced">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="canonical" href="/">
    <link rel="alternate" hreflang="x-default" href="/">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" integrity="sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ==" crossorigin="">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href={% static "css/media-queries.css" %}>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
</head>

<body class="{% block body_class %} {% endblock %}">
{% block header %}
    <!-- Top menu -->
    {% include "responsive/header.html" %}
{% endblock %}

<!-- Top content -->

{% block content %}
    <div class="top-content" style="position: relative; z-index: 0; background: none;" data-backstretch-src="{% static "img/1.jpg" %}">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 text wow fadeInLeft animated" style="visibility: visible; animation-name: fadeInLeft;">
                    <h1>{% trans "Welcome to Spacesmap." %}</h1>
                    <div class="description">
                        <p>Are you coworking yet?</p>
                        <p>Explore over 5500 coworking spaces</p>
                    </div>
                    <div class="top-buttons">
                        <a class="btn btn-link-1 scroll-link active" href="#sign-in">Login</a>
                        <a class="btn btn-link-1 scroll-link" href="#sign-up">Sign up</a>
                    </div>
                </div>

                <div class="col-sm-5 col-sm-offset-1 r-form-1-box wow fadeInUp animated" style="visibility: visible; animation-name: fadeInUp;">
                    {#						<div class="r-form-1-top">#}
                    {#							<h3>Fill in the form below to get instant access now!</h3>#}
                    {#						</div>#}
                    <div class="r-form-1-bottom">
                        {% login_form %}
                        {% sign_up_form %}
                    </div>
                </div>

            </div>

        </div>
    </div>
        <div class="backstretch" style="left: 0px; top: 0px; overflow: hidden; margin: 0px; padding: 0px; height: 704px; width: 1364px; z-index: -999998; position: absolute;">
            <img src="{% static "img/1.jpg" %}" style="position: absolute; margin: 0px; padding: 0px; border: none; width: 1364px; height: 909.333px; max-height: none; max-width: none; z-index: -999999; left: 0px; top: -102.667px;">
        </div>
{% endblock %}
</div>
{% block footer %}
    {% include "responsive/footer.html" %}
{% endblock %}


<!-- MODAL: Terms and Conditions -->
<div class="modal fade" id="modal-terms" tabindex="-1" role="dialog" aria-labelledby="modal-terms-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span><span class="sr-only">Close</span>
                </button>
                <h2 class="modal-title" id="modal-terms-label">Terms and Conditions</h2>
            </div>
            <div class="modal-body">
                <p>Please read carefully the terms and conditions for using our product below:</p>
                <h3>1. Dolor sit amet</h3>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                    labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.
                </p>
                <ul>
                    <li>Easy To Use</li>
                    <li>Awesome Design</li>
                    <li>Cloud Based</li>
                </ul>
                <p>
                    Ut wisi enim ad minim veniam, <a href="#">quis nostrud exerci tation</a> ullamcorper suscipit lobortis nisl ut aliquip ex ea
                    commodo consequat nostrud tation.
                </p>
                <h3>2. Sed do eiusmod</h3>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                    labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.
                </p>
                <h3>3. Nostrud exerci tation</h3>
                <p>
                    Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea
                    commodo consequat nostrud tation.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                    labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn" data-dismiss="modal">I Read it &amp; I Agree</button>
            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<!-- Javascript -->




{#<script src="{% static "js/my_common.js" %}"></script>#}

<script src="{% static 'js/jquery-1.11.1.min.js' %}" type="text/javascript"></script>
{% addtoblock "js" %}
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js" integrity="sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log==" crossorigin=""></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static "js/retina-1.1.0.min.js" %}"></script>
    <script src="{% static "js/wow.min.js" %}"></script>
    <script src="{% static "js/jquery.backstretch.min.js" %}"></script>
    <script src="{% static "js/scripts.js" %}"></script>
    <script src="{% static "js/map.js" %}"></script>
{% endaddtoblock %}

{% render_block "js" %}
<!--[if lt IE 10]>
            <script src="assets/js/placeholder.js"></script>
        <![endif]-->



<script type="text/javascript">


  $(function() {

    {#      $("[name=f_location]").autocomplete({#}
    $("#search-query").autocomplete({
      source: function(request, response) {
        $("#place_id").val(0);
        $("#search_place").val(0);
        $.ajax({
          url: '{% url "search:search_autocomplete" %}',
          dataType: "json",
          type: "GET",
          data: {
            search : request.term
          },
          success: function(data) {
            response(data);
            /*if(data.length>0){
              var prefix = $('#f_location').val().toLowerCase();
              var first_item = data[0].value.toLowerCase();
              if(first_item.slice(0, prefix.length) == prefix){
                $('#f_location').val(data[0].value);
                $('#f_location').selectRange(prefix.length,first_item.length);
              }
            }*/
          }
        });
      },minLength:1,
      messages: {
        noResults: '',
        results: function() {}
      },appendTo: "#f_aucomplete",
      select: function (event, ui) {
        console.log(ui.item.coworkspace_url);
        if (ui.item.coworkspace_url != '')
          window.location = ui.item.coworkspace_url;
      }
    }).autocomplete( "instance" )._renderItem = function( ul, item ) {
      var loc_icon = '<i class="fa fa-buildingui"></i>';
      var view_all = '';
      {#        if(item.loc==1)#}
      {#          loc_icon = '<i class="fa fa-globeui"></i>';#}
      {#        if((item.loc==2) || (item.loc==2.5))#}
      {#          loc_icon = '<i class="fa fa-map-markerui"></i>';#}
      {#        if(item.loc==5)#}
      {#          loc_icon = '<i class="fa fa-map-markerui"></i>';#}
      {#        if(item.loc==10)#}
      {#          loc_icon = '<i class="fa fa-map-markerui"></i>';#}
      {#        if(item.loc==0){#}
      {#          loc_icon = "";#}
      {#          view_all = 'class="search_view_results_div pade_none"';#}
      {#        }#}
      return $( "<li "+view_all+">" ).append( loc_icon + item.label ).appendTo( ul );
    };
  });

  var buildUrl = function(base, key, value) {
    var sep = (base.indexOf('?') > -1) ? '&' : '?';
    return base + sep + key + '=' + value;
  };

  function submitSearch() {

    var search = location.search.substring(1);
    var params = {};
    if (search)
      params = JSON.parse('{"' + decodeURI(search).replace(/"/g, '\\"').replace(/&/g, '","').replace(/=/g,'":"') + '"}');

    var new_url = '{% url "main:search" %}';
    params['q'] = $("#search-query").val();
    for (var key in params) {
      if (params.hasOwnProperty(key)) {
        new_url = buildUrl(new_url, key, params[key]);
      }
    }

    window.location = new_url;
  }

  $("#search-query").keypress(function(event) {
    if (event.which == 13) {
      event.preventDefault();
      submitSearch();
    }
  });



</script>
{% block script %}

{% endblock %}

</body></html>

coworker/templates/responsive/index.html
{% extends "responsive/base.html" %}

{% block body_class %} index {% endblock %}