config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.conf.urls.i18n import i18n_patterns
from ajax_select import urls as ajax_select_urls


#
# blog_urls = ([
#     url(r'^', include('zinnia.urls.capabilities')),
#     url(r'^search/', include('zinnia.urls.search')),
#     url(r'^sitemap/', include('zinnia.urls.sitemap')),
#     url(r'^trackback/', include('zinnia.urls.trackback')),
#     url(r'^blog/tags/', include('zinnia.urls.tags')),
#     url(r'^blog/feeds/', include('zinnia.urls.feeds')),
#     url(r'^blog/random/', include('zinnia.urls.random')),
#     url(r'^blog/authors/', include('zinnia.urls.authors')),
#     url(r'^blog/categories/', include('zinnia.urls.categories')),
#     url(r'^blog/comments/', include('zinnia.urls.comments')),
#     url(r'^blog/', include('zinnia.urls.entries')),
#     url(r'^blog/', include('zinnia.urls.archives')),
#     url(r'^blog/', include('zinnia.urls.shortlink')),
#     url(r'^blog/', include('zinnia.urls.quick_entry'))
# ], 'zinnia')
#



urlpatterns = i18n_patterns(
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # User management
    url(r'^select2/', include('django_select2.urls')),
    url(r'^ajax_select/', include(ajax_select_urls)),
    url(r'^', include('coworker.main.urls', namespace='main')),
    # url(r'^(?P<country>[\w-]+)/', include('coworker.place.urls', namespace='place')),
    url(r'^profile/', include('coworker.users.urls', namespace='users')),

    url(r'^accounts/', include('allauth.urls')),

    url(r'^places/', include('coworker.place.urls', namespace='place')),
    url(r'^events/', include('coworker.events.urls', namespace='events')),
    url(r'^services/', include('coworker.services.urls', namespace='services')),
    # url(r'^', include(blog_urls)),
    url(r'^lab/', include('coworker.lab.urls', namespace='lab')),
    url(r'^search/', include('coworker.search.urls', namespace='search')),
    url(r'^social/', include('coworker.social.urls', namespace='social')),


    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^comments/', include('django_comments.urls')),
    # Your stuff: custom urls includes go here


) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        url(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

coworker/lab/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^$', views.ArticleListView.as_view(), name='index'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        views.EntryDetail.as_view(),
        name='entry_detail'),
]

coworker/main/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^$', view=views.Index.as_view(), name='index'),
    url(r'^search/$', view=views.SearchView.as_view(), name='search'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^cities/$', TemplateView.as_view(template_name='pages/cities.html'), name='cities'),
    url(r'^team/$', TemplateView.as_view(template_name='pages/team.html'), name='team'),
    url(r'^contact/$', TemplateView.as_view(template_name='pages/contact.html'), name='contact'),
    url(r'^reviews/$', TemplateView.as_view(template_name='pages/reviews.html'), name='reviews'),
    url(r'^terms/$', TemplateView.as_view(template_name='pages/terms.html'), name='terms'),
    url(r'^privacy-policy/$', TemplateView.as_view(template_name='pages/privacy-policy.html'), name='privacy-policy'),
    url(r'^help/$', TemplateView.as_view(template_name='pages/help.html'), name='help'),
]

coworker/place/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^card/api/(?P<pk>\d+)/$', view=views.PlaceDetailApiView.as_view(), name='detail_card'),
    url(r'^map/api/$', view=views.PlaceMapApiView.as_view(), name='map_api'),


    #url(r'^list-space/success/$', view=views.PlaceAddSuccess.as_view(), name='list-space-success'),


    #photo edit urls


    url(r'^search/autocomplete/$', views.autocomplete),

    url(r'^search/$', view=views.SearchList.as_view(), name='search'),
    url(r'^search/(?P<country>[\w-]+)/', view=views.SearchList.as_view(), name='search-country'), #HERE REMOVED $


    url(r'^(?P<country>[\w-]+)/$', view=views.PlaceCountryList.as_view(), name='country'),
    url(r'^(?P<country>[\w-]+)/(?P<city>[\w-]+)/$', view=views.PlaceCityList.as_view(), name='city'),
    url(r'^(?P<country>[\w-]+)/(?P<city>[\w-]+)/(?P<place>[\w-]+)/$',
        view=views.PlaceView.as_view(), name='place'),
    # url(r'^(?P<city>[\w-]+)/(?P<place>.*)/$', view=views.Place.as_view(), name='place'),


]

coworker/lab/models.py
"""Base entry models for Zinnia"""
import os
from django.apps import apps
from django.conf import settings
from mptt.managers import TreeManager
from mptt.models import MPTTModel
from mptt.models import TreeForeignKey

from django.contrib.sites.models import Site
from django.db import models
from django.db.models import Q
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.utils.html import strip_tags
from django.utils.text import Truncator
from django.utils.translation import ugettext_lazy as _

import django_comments as comments
from django_comments.models import CommentFlag

from tagging.fields import TagField
from tagging.utils import parse_tag_input

from coworker.lab.flags import PINGBACK
from coworker.lab.flags import TRACKBACK
from .managers import DRAFT, HIDDEN, PUBLISHED
from .managers import EntryPublishedManager
from coworker.lab.markups import html_format
from coworker.lab.preview import HTMLPreview
from .settings import AUTO_CLOSE_COMMENTS_AFTER
from .settings import AUTO_CLOSE_PINGBACKS_AFTER
from .settings import AUTO_CLOSE_TRACKBACKS_AFTER
from .settings import ENTRY_CONTENT_TEMPLATES
from .settings import ENTRY_DETAIL_TEMPLATES
from .settings import UPLOAD_TO
from tinymce.models import HTMLField

# from coworker.lab.url_shortener import get_url_shortener

from .managers import EntryRelatedPublishedManager
from .managers import entries_published


@python_2_unicode_compatible
class Category(MPTTModel):
    """
    Simple model for categorizing entries.
    """

    title = models.CharField(
        _('title'), max_length=255)

    slug = models.SlugField(
        _('slug'), unique=True, max_length=255,
        help_text=_("Used to build the category's URL."))

    description = models.TextField(
        _('description'), blank=True)

    parent = TreeForeignKey(
        'self',
        related_name='children',
        null=True, blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_('parent category'))

    objects = TreeManager()
    published = EntryRelatedPublishedManager()

    def entries_published(self):
        """
        Returns category's published entries.
        """
        return entries_published(self.entries)

    @property
    def tree_path(self):
        """
        Returns category's tree path
        by concatening the slug of his ancestors.
        """
        if self.parent_id:
            return '/'.join(
                [ancestor.slug for ancestor in self.get_ancestors()] +
                [self.slug])
        return self.slug

    def get_absolute_url(self):
        """
        Builds and returns the category's URL
        based on his tree path.
        """
        return reverse('zinnia:category_detail', args=(self.tree_path,))

    def __str__(self):
        return self.title

    class Meta:
        """
        Category's meta informations.
        """
        ordering = ['title']
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    class MPTTMeta:
        """
        Category MPTT's meta informations.
        """
        order_insertion_by = ['title']




@python_2_unicode_compatible
class CoreEntry(models.Model):
    """
    Abstract core entry model class providing
    the fields and methods required for publishing
    content over time.
    """
    STATUS_CHOICES = ((DRAFT, _('draft')),
                      (HIDDEN, _('hidden')),
                      (PUBLISHED, _('published')))

    title = models.CharField(
        _('title'), max_length=255)

    slug = models.SlugField(
        _('slug'), max_length=255,
        unique_for_date='publication_date',
        help_text=_("Used to build the entry's URL."))

    status = models.IntegerField(
        _('status'), db_index=True,
        choices=STATUS_CHOICES, default=DRAFT)

    publication_date = models.DateTimeField(
        _('publication date'),
        db_index=True, default=timezone.now,
        help_text=_("Used to build the entry's URL."))

    start_publication = models.DateTimeField(
        _('start publication'),
        db_index=True, blank=True, null=True,
        help_text=_('Start date of publication.'))

    end_publication = models.DateTimeField(
        _('end publication'),
        db_index=True, blank=True, null=True,
        help_text=_('End date of publication.'))

    sites = models.ManyToManyField(
        Site,
        related_name='entries',
        verbose_name=_('sites'),
        help_text=_('Sites where the entry will be published.'))

    creation_date = models.DateTimeField(
        _('creation date'),
        default=timezone.now)

    last_update = models.DateTimeField(
        _('last update'), default=timezone.now)

    objects = models.Manager()
    published = EntryPublishedManager()

    @property
    def is_actual(self):
        """
        Checks if an entry is within his publication period.
        """
        now = timezone.now()
        if self.start_publication and now < self.start_publication:
            return False

        if self.end_publication and now >= self.end_publication:
            return False
        return True

    @property
    def is_visible(self):
        """
        Checks if an entry is visible and published.
        """
        return self.is_actual and self.status == PUBLISHED

    @property
    def previous_entry(self):
        """
        Returns the previous published entry if exists.
        """
        return self.previous_next_entries[0]

    @property
    def next_entry(self):
        """
        Returns the next published entry if exists.
        """
        return self.previous_next_entries[1]

    @property
    def previous_next_entries(self):
        """
        Returns and caches a tuple containing the next
        and previous published entries.
        Only available if the entry instance is published.
        """
        previous_next = getattr(self, 'previous_next', None)

        if previous_next is None:
            if not self.is_visible:
                previous_next = (None, None)
                setattr(self, 'previous_next', previous_next)
                return previous_next

            entries = list(self.__class__.published.all())
            index = entries.index(self)
            try:
                previous = entries[index + 1]
            except IndexError:
                previous = None

            if index:
                _next = entries[index - 1]
            else:
                _next = None
            previous_next = (previous, _next)
            setattr(self, 'previous_next', previous_next)
        return previous_next

    @property
    def short_url(self):
        """
        Returns the entry's short url.
        """
        # return get_url_shortener()(self)

    def save(self, *args, **kwargs):
        """
        Overrides the save method to update the
        the last_update field.
        """
        self.last_update = timezone.now()
        super(CoreEntry, self).save(*args, **kwargs)

    def get_absolute_url(self):
        """
        Builds and returns the entry's URL based on
        the slug and the creation date.
        """
        publication_date = self.publication_date
        if timezone.is_aware(publication_date):
            publication_date = timezone.localtime(publication_date)
        return reverse('lab:entry_detail', kwargs={
            'year': publication_date.strftime('%Y'),
            'month': publication_date.strftime('%m'),
            'day': publication_date.strftime('%d'),
            'slug': self.slug})

    def __str__(self):
        return '%s: %s' % (self.title, self.get_status_display())

    class Meta:
        """
        CoreEntry's meta informations.
        """
        abstract = True
        ordering = ['-publication_date']
        get_latest_by = 'publication_date'
        verbose_name = _('entry')
        verbose_name_plural = _('entries')
        index_together = [['slug', 'publication_date'],
                          ['status', 'publication_date',
                           'start_publication', 'end_publication']]
        permissions = (('can_view_all', 'Can view all entries'),
                       ('can_change_status', 'Can change status'),
                       ('can_change_author', 'Can change author(s)'), )


class ContentEntry(models.Model):
    """
    Abstract content model class providing field
    and methods to write content inside an entry.
    """
    content = HTMLField(_('content'), blank=True)

    @property
    def html_content(self):
        """
        Returns the "content" field formatted in HTML.
        """
        return html_format(self.content)

    @property
    def html_preview(self):
        """
        Returns a preview of the "content" field or
        the "lead" field if defined, formatted in HTML.
        """
        return HTMLPreview(self.html_content,
                           getattr(self, 'html_lead', ''))

    @property
    def word_count(self):
        """
        Counts the number of words used in the content.
        """
        return len(strip_tags(self.html_content).split())

    class Meta:
        abstract = True


class DiscussionsEntry(models.Model):
    """
    Abstract discussion model class providing
    the fields and methods to manage the discussions
    (comments, pingbacks, trackbacks).
    """
    comment_enabled = models.BooleanField(
        _('comments enabled'), default=True,
        help_text=_('Allows comments if checked.'))
    pingback_enabled = models.BooleanField(
        _('pingbacks enabled'), default=True,
        help_text=_('Allows pingbacks if checked.'))
    trackback_enabled = models.BooleanField(
        _('trackbacks enabled'), default=True,
        help_text=_('Allows trackbacks if checked.'))

    comment_count = models.IntegerField(
        _('comment count'), default=0)

coworker/main/models.py
from django.db import models

coworker/search/models.py
from django.db import models

# Create your models here.

coworker/social/models.py
from django.db import models
from django.utils import timezone

from coworker.users.models import User


class Tweet(models.Model):
    user = models.ForeignKey(User, related_name='tweets')
    created = models.DateTimeField(default=timezone.now)
    body = models.TextField()

coworker/social/forms.py
from .models import Tweet
from django import forms


class TweetForm(forms.ModelForm):

    class Meta:
        model = Tweet
        fields = ['body']

coworker/lab/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, TemplateView, CreateView, FormView
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, TemplateView, CreateView, FormView
from django.views import View
from .models import Entry
# Create your views here.
# aricles


class ArticleListView(View):
    template_name = "lab/lab_index.html"

    def get(self, request, *args, **kwargs):
        ctx = {}
        ctx['articles'] = Entry.objects.all()
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        #TODO figure out why and where called post method
        return self.get(request, *args, **kwargs)



class EntryDetail(DetailView):
    template_name = "lab/entry_detail.html"
    model = Entry
    context_object_name = "article"
# class ArticleListView(Views):
#     model = Entry
#     context_object_name = "articles"
#     template_name = "lab/lab_index.html"
#

coworker/templates/zinnia/_entry_detail.html
{% extends "zinnia/_entry_detail_base.html" %}

coworker/templates/zinnia/base.html
{% extends "zinnia/skeleton.html" %}
{% load i18n %}
{% load zinnia %}

{% block meta-keywords %}{% get_tags as entry_tags %}{{ entry_tags|join:", "}}{% endblock meta-keywords %}

{% block meta %}
    <meta name="generator" content="Zinnia {{ ZINNIA_VERSION }}" />
{% endblock meta %}

{% block link %}
    <link rel="index" href="{% url 'zinnia:entry_archive_index' %}" />
    <link rel="author" type="text/plain" href="{% url 'zinnia:humans' %}" />
    <link rel="EditURI" type="application/rsd+xml" href="{% url 'zinnia:rsd' %}" />
    <link rel="wlwmanifest" type="application/wlwmanifest+xml" href="{% url 'zinnia:wlwmanifest' %}" />
    <link rel="search" type="application/opensearchdescription+xml" title="Zinnia's Weblog" href="{% url 'zinnia:opensearch' %}" />
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS feed of last entries" %}" href="{% url 'zinnia:entry_feed' %}" />
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS feed of last discussions" %}" href="{% url 'zinnia:discussion_feed' %}" />
    {% get_archives_entries "zinnia/tags/entries_archives_link.html" %}
{% endblock link %}

{% block breadcrumbs %}
  {% trans "Blog" as root_name %}
  {% zinnia_breadcrumbs root_name %}
{% endblock breadcrumbs %}

{% block sidebar %}
<aside id="widget-welcome" class="widget">
  <h3>{% trans "Welcome!" %}</h3>
  <p>
    {% trans "This simple theme is the default appearance of Zinnia." %}
  </p>
  <p>
    {% trans "Don't hesitate to override the template <strong>zinnia/base.html</strong> to start <a href='http://docs.django-blog-zinnia.com/en/latest/how-to/customize_look_and_feel.html'>customizing your Weblog</a>." %}
  </p>
</aside>
<aside id="widget-categories" class="widget">
  <h3>
    <a href="{% url 'zinnia:category_list' %}">{% trans "Categories" %}</a>
  </h3>
  {% get_categories %}
</aside>
<aside id="widget-authors" class="widget">
  <h3>
    <a href="{% url 'zinnia:author_list' %}">{% trans "Authors" %}</a>
  </h3>
  {% get_authors %}
</aside>
<aside id="widget-calendar" class="widget">
  <h3>{% trans "Calendar" %}</h3>
  {% get_calendar_entries %}
</aside>
<aside id="widget-tags" class="widget">
  <h3>
    <a href="{% url 'zinnia:tag_list' %}">{% trans "Tags" %}</a>
  </h3>
  {% get_tag_cloud %}
</aside>
<aside id="widget-recents" class="widget">
  <h3>{% trans "Recent entries" %}</h3>
  {% get_recent_entries %}
</aside>
<aside id="widget-comments" class="widget">
  <h3>{% trans "Recent comments" %}</h3>
  {% get_recent_comments %}
</aside>
<aside id="widget-linkbacks" class="widget">
  <h3>{% trans "Recent linkbacks" %}</h3>
  {% get_recent_linkbacks %}
</aside>
<aside id="widget-randoms" class="widget">
  <h3>{% trans "Random entries" %}</h3>
  {% get_random_entries %}
</aside>
<aside id="widget-populars" class="widget">
  <h3>{% trans "Popular entries" %}</h3>
  {% get_popular_entries %}
</aside>
<aside id="widget-archives" class="widget">
  <h3>{% trans "Archives" %}</h3>
  {% get_archives_entries_tree %}
</aside>
{% if user.is_authenticated %}
<aside id="widget-tools" class="widget">
  <h3>{% trans "Tools" %}</h3>
  <ul>
    {% if perms.zinnia %}
    <li>
      <a href="{% url 'admin:app_list' 'zinnia' %}" title="{% trans "Dashboard" %}">
        {% trans "Dashboard" %}
      </a>
    </li>
    {% endif %}
    {% if perms.zinnia.add_entry %}
    <li>
      <a href="{% url 'admin:zinnia_entry_add' %}" title="{% trans "Post an entry" %}">
        {% trans "Post an entry" %}
      </a>
    </li>
    {% endif %}
    {% block admin-tools %}
    {% endblock admin-tools %}
    <li>
      <a href="{% url 'admin:logout' %}" title="{% trans "Log out" %}">
        {% trans "Log out" %}
      </a>
    </li>
  </ul>
</aside>
{% endif %}
{% endblock sidebar %}

coworker/templates/zinnia/entry_archive.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}
{% load zinnia %}

{% block meta-description %}{% trans "Last entries" %}{% endblock meta-description %}

{% block title %}{% trans "Last entries" %}{% endblock title %}

{% block body-class %}{{ block.super }} archive index {% now "\y\e\a\r-Y \m\o\n\t\h-m \w\e\ek-W \d\a\y-d" %}{% endblock body-class %}

{% block slider %}
{% get_featured_entries template="zinnia/tags/entries_slider.html" %}
{% endblock slider %}

{% block content-related %}
{% if date_list %}
<h2>{% trans "Yearly archives" %}</h2>
<ul>
  {% for date in date_list %}
  <li>
    <a href="{% url 'zinnia:entry_archive_year' date|date:"Y" %}" rel="archives">{{ date|date:"Y" }}</a>
  </li>
  {% endfor %}
</ul>
{% endif %}
{% endblock content-related %}

coworker/templates/zinnia/entry_archive_day.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}
{% load zinnia %}

{% block meta-description %}{% trans "Archives" %} {{ day|date:"DATE_FORMAT" }}{% endblock meta-description %}

{% block title %}{% trans "Archives" %} {{ day|date:"DATE_FORMAT" }}{% endblock title %}

{% block body-class %}{{ block.super }} archive date day year-{{ day|date:"Y" }} month-{{ day|date:"m" }} week-{{ day|date:"W" }} day-{{ day|date:"d" }}{% endblock body-class %}

{% block content-title %}
<h1>{% trans "Archives" %} {{ day|date:"DATE_FORMAT" }}</h1>
{% endblock content-title %}

{% block content-related %}
{% if previous_day %}
<h3>{% trans "Previous day" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_day' previous_day|date:"Y" previous_day|date:"m" previous_day|date:"d" %}" rel="archives">{{ previous_day|date:"DATE_FORMAT" }}</a>
</p>
{% endif %}
{% if next_day %}
<h3>{% trans "Next day" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_day' next_day|date:"Y" next_day|date:"m" next_day|date:"d" %}" rel="archives">{{ next_day|date:"DATE_FORMAT" }}</a>
</p>
{% endif %}

<h3>{% trans "Archives" %}</h3>
<ul>
  <li>
    <a href="{% url 'zinnia:entry_archive_year' day|date:"Y" %}" rel="archives">{{ day|date:"Y" }}</a>
  </li>
  <li>
    <a href="{% url 'zinnia:entry_archive_week' day|date:"Y" day|week_number %}" rel="archives">
      {% blocktrans with year=day|date:"Y" week_number=day|week_number %}Week {{ week_number }} of {{ year }}{% endblocktrans %}
    </a>
  </li>
  {% if previous_month %}
  <li>
    <a href="{% url 'zinnia:entry_archive_month' previous_month|date:"Y" previous_month|date:"m" %}" rel="archives">{{ previous_month|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
  {% endif %}
  <li>
    <a href="{% url 'zinnia:entry_archive_month' day|date:"Y" day|date:"m" %}" rel="archives">{{ day|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
  {% if next_month %}
  <li>
    <a href="{% url 'zinnia:entry_archive_month' next_month|date:"Y" next_month|date:"m" %}" rel="archives">{{ next_month|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
  {% endif %}
</ul>
{% endblock content-related %}

coworker/templates/zinnia/entry_archive_month.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}

{% block meta-description %}{% trans "Archives" %} {{ month|date:"YEAR_MONTH_FORMAT" }}{% endblock meta-description %}

{% block title %}{% trans "Archives" %} {{ month|date:"YEAR_MONTH_FORMAT" }}{% endblock title %}

{% block body-class %}{{ block.super }} archive date month year-{{ month|date:"Y" }} month-{{ month|date:"m" }}{% endblock body-class %}

{% block content-title %}
<h1>{% trans "Archives" %} {{ month|date:"YEAR_MONTH_FORMAT" }}</h1>
{% endblock content-title %}

{% block content-related %}
{% if date_list %}
<h2>{% trans "Daily archives" %}</h2>
<ul>
  {% for date in date_list %}
  <li>
    <a href="{% url 'zinnia:entry_archive_day' date|date:"Y" date|date:"m" date|date:"d" %}" rel="archives">{{ date|date:"DATE_FORMAT" }}</a>
  </li>
  {% endfor %}
</ul>
{% endif %}
{% if previous_month %}
<h3>{% trans "Previous month" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_month' previous_month|date:"Y" previous_month|date:"m" %}" rel="archives">{{ previous_month|date:"YEAR_MONTH_FORMAT" }}</a>
</p>
{% endif %}
{% if next_month %}
<h3>{% trans "Next month" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_month' next_month|date:"Y" next_month|date:"m" %}" rel="archives">{{ next_month|date:"YEAR_MONTH_FORMAT" }}</a>
</p>
{% endif %}
<h3>{% trans "Archives" %}</h3>
<ul>
  <li>
    <a href="{% url 'zinnia:entry_archive_year' month|date:"Y" %}" rel="archives">{{ month|date:"Y" }}</a>
  </li>
</ul>
{% endblock content-related %}

coworker/templates/zinnia/entry_archive_week.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}
{% load zinnia %}

{% block meta-description %}{% blocktrans with year=week|date:"Y" week_number=week|week_number %}Archives week {{ week_number }} of {{ year }}{% endblocktrans %}{% endblock meta-description %}

{% block title %}{% blocktrans with year=week|date:"Y" week_number=week|week_number %}Archives week {{ week_number }} of {{ year }}{% endblocktrans %}{% endblock title %}

{% block body-class %}{{ block.super }} archive date week year-{{ week|date:"Y" }} month-{{ week|date:"m" }} week-{{ week|week_number }}{% endblock body-class %}

{% block content-title %}
<h1>{% blocktrans with year=week|date:"Y" week_number=week|week_number %}Archives week {{ week_number }} of {{ year }}{% endblocktrans %}</h1>
<h2>{{ week|date:"DATE_FORMAT" }} - {{ week_end_day|date:"DATE_FORMAT" }}</h2>
{% endblock content-title %}

{% block content-related %}
{% if date_list %}
<h2>{% trans "Daily archives" %}</h2>
<ul>
  {% for date in date_list %}
  <li>
    <a href="{% url 'zinnia:entry_archive_day' date|date:"Y" date|date:"m" date|date:"d" %}" rel="archives">{{ date|date:"DATE_FORMAT" }}</a>
  </li>
  {% endfor %}
</ul>
{% endif %}
{% if previous_week %}
<h3>{% trans "Previous week" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_week' previous_week|date:"Y" previous_week|week_number %}" rel="archives">
    {% blocktrans with year=previous_week|date:"Y" week_number=previous_week|week_number %}Week {{ week_number }} of {{ year }}{% endblocktrans %}
  </a>
</p>
{% endif %}
{% if next_week %}
<h3>{% trans "Next week" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_week' next_week|date:"Y" next_week|week_number %}" rel="archives">
    {% blocktrans with year=next_week|date:"Y" week_number=next_week|week_number %}Week {{ week_number }} of {{ year }}{% endblocktrans %}
  </a>
</p>
{% endif %}
<h3>{% trans "Archives" %}</h3>
<ul>
  <li>
    <a href="{% url 'zinnia:entry_archive_year' week|date:"Y" %}" rel="archives">{{ week|date:"Y" }}</a>
  </li>
  <li>
    <a href="{% url 'zinnia:entry_archive_month' week|date:"Y" week|date:"m" %}" rel="archives">{{ week|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
<ul>
{% endblock content-related %}

coworker/templates/zinnia/entry_detail.html
{% extends "zinnia/entry_detail_base.html" %}