config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.conf.urls.i18n import i18n_patterns
from ajax_select import urls as ajax_select_urls


#
# blog_urls = ([
#     url(r'^', include('zinnia.urls.capabilities')),
#     url(r'^search/', include('zinnia.urls.search')),
#     url(r'^sitemap/', include('zinnia.urls.sitemap')),
#     url(r'^trackback/', include('zinnia.urls.trackback')),
#     url(r'^blog/tags/', include('zinnia.urls.tags')),
#     url(r'^blog/feeds/', include('zinnia.urls.feeds')),
#     url(r'^blog/random/', include('zinnia.urls.random')),
#     url(r'^blog/authors/', include('zinnia.urls.authors')),
#     url(r'^blog/categories/', include('zinnia.urls.categories')),
#     url(r'^blog/comments/', include('zinnia.urls.comments')),
#     url(r'^blog/', include('zinnia.urls.entries')),
#     url(r'^blog/', include('zinnia.urls.archives')),
#     url(r'^blog/', include('zinnia.urls.shortlink')),
#     url(r'^blog/', include('zinnia.urls.quick_entry'))
# ], 'zinnia')
#



urlpatterns = i18n_patterns(
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # User management
    url(r'^select2/', include('django_select2.urls')),
    url(r'^ajax_select/', include(ajax_select_urls)),
    url(r'^', include('coworker.main.urls', namespace='main')),
    # url(r'^(?P<country>[\w-]+)/', include('coworker.place.urls', namespace='place')),
    url(r'^profile/', include('coworker.users.urls', namespace='users')),

    url(r'^accounts/', include('allauth.urls')),

    url(r'^places/', include('coworker.place.urls', namespace='place')),
    url(r'^events/', include('coworker.events.urls', namespace='events')),
    url(r'^services/', include('coworker.services.urls', namespace='services')),
    # url(r'^', include(blog_urls)),
    url(r'^lab/', include('coworker.lab.urls', namespace='lab')),
    url(r'^search/', include('coworker.search.urls', namespace='search')),
    url(r'^social/', include('coworker.social.urls', namespace='social')),


    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^comments/', include('django_comments.urls')),
    # Your stuff: custom urls includes go here


) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        url(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

coworker/lab/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^$', views.ArticleListView.as_view(), name='index'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        views.EntryDetail.as_view(),
        name='entry_detail'),
]

coworker/main/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^$', view=views.Index.as_view(), name='index'),
    url(r'^search/$', view=views.SearchView.as_view(), name='search'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^cities/$', TemplateView.as_view(template_name='pages/cities.html'), name='cities'),
    url(r'^team/$', TemplateView.as_view(template_name='pages/team.html'), name='team'),
    url(r'^contact/$', TemplateView.as_view(template_name='pages/contact.html'), name='contact'),
    url(r'^reviews/$', TemplateView.as_view(template_name='pages/reviews.html'), name='reviews'),
    url(r'^terms/$', TemplateView.as_view(template_name='pages/terms.html'), name='terms'),
    url(r'^privacy-policy/$', TemplateView.as_view(template_name='pages/privacy-policy.html'), name='privacy-policy'),
    url(r'^help/$', TemplateView.as_view(template_name='pages/help.html'), name='help'),
]

coworker/place/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^card/api/(?P<pk>\d+)/$', view=views.PlaceDetailApiView.as_view(), name='detail_card'),
    url(r'^map/api/$', view=views.PlaceMapApiView.as_view(), name='map_api'),


    #url(r'^list-space/success/$', view=views.PlaceAddSuccess.as_view(), name='list-space-success'),


    #photo edit urls


    url(r'^search/autocomplete/$', views.autocomplete),

    url(r'^search/$', view=views.SearchList.as_view(), name='search'),
    url(r'^search/(?P<country>[\w-]+)/', view=views.SearchList.as_view(), name='search-country'), #HERE REMOVED $


    url(r'^(?P<country>[\w-]+)/$', view=views.PlaceCountryList.as_view(), name='country'),
    url(r'^(?P<country>[\w-]+)/(?P<city>[\w-]+)/$', view=views.PlaceCityList.as_view(), name='city'),
    url(r'^(?P<country>[\w-]+)/(?P<city>[\w-]+)/(?P<place>[\w-]+)/$',
        view=views.PlaceView.as_view(), name='place'),
    # url(r'^(?P<city>[\w-]+)/(?P<place>.*)/$', view=views.Place.as_view(), name='place'),


]

coworker/main/models.py
from django.db import models

coworker/search/models.py
from django.db import models

# Create your models here.

coworker/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.utils.functional import cached_property
from django.contrib.staticfiles.templatetags.staticfiles import static



class UserTags(models.Model):
    name = models.CharField(blank=True, max_length=255)

    def __str__(self):
        return self.name


class Indastry(models.Model):
    name = models.CharField(blank=True, max_length=255)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class User(AbstractUser):
    SPACES = 'sp'
    ORGANIZATIONS = 'or'
    STARTUPS = 'st'
    INVESTORS = 'in'

    USER_TYPE_CHOICES = (
        (SPACES, _('Spaces')),
        (ORGANIZATIONS, _('Organizations')),
        (STARTUPS, _('Startups')),
        (INVESTORS, _('Investors')),
    )

    name = models.CharField(_('Name of User'), blank=True, max_length=255)
    profile_image = models.ImageField(_(u"User image"), upload_to='profile_pictures', blank=True, null=True)
    birth_day = models.DateField(_("Birth day"), null=True, blank=True)
    aboutme = models.TextField(_("About me"), null=True, blank=True)
    business_name = models.TextField(_("Business name"), null=True, blank=True)
    registration = models.DateField(_("Registration"), null=True, blank=True)
    business_summarize = models.TextField(_("Business summarize "), null=True, blank=True)
    industries = models.ManyToManyField(Indastry, blank=True, related_name="user")
    tags = models.ManyToManyField(UserTags, blank=True, related_name="user")
    user_type = models.CharField(max_length=2, choices=USER_TYPE_CHOICES, blank=True)

    place = models.ForeignKey('place.Place', blank=True, null=True)

    followers = models.ManyToManyField('self', related_name='follow', symmetrical=False, blank=True)

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

    # def get_absolute_url(self):
    #     return reverse('users:detail', kwargs={'username': self.username})

    def get_tags(self):
        return ", ".join(list(self.tags.values_list("name",  flat=True)))

    def get_industries(self):
        return ", ".join(list(self.industries.values_list("name",  flat=True)))

    # def get_user_type(self):
    #     return
    @cached_property
    def profile_image_url(self):
        if self.profile_image:
            return self.profile_image.url
        else:
            return static('img/no-user-image.gif')

    def full_name(self):
        return "{} {}".format(self.first_name.capitalize(), self.last_name.capitalize())


    def is_space_owner(self):
        return self.user_type == self.SPACE_OWNER

    def is_startup_owner(self):
        return self.user_type == self.STARTUP_OWNER

    def get_user_type(self):
        return self.user_type

    @cached_property
    def cs_description(self):
        return self.aboutme or ""


    def get_name(self):
        return self.username


    def get_main_photo(self):
        try:
            return self.profile_image.url
        except Exception as e:
            print(e)
            return

    def follow_url(self):
        return reverse("social:follow", kwargs={"pk": self.pk})

    def get_followers(self):
        return self.followers.all()

coworker/social/forms.py
from .models import Tweet
from django import forms


class TweetForm(forms.ModelForm):

    class Meta:
        model = Tweet
        fields = ['body']

coworker/events/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DetailView, ListView, TemplateView
from django.views.decorators.csrf import csrf_exempt
from rest_framework.response import Response

from config.es_client import es_client

from rest_framework_elasticsearch import es_views, es_pagination, es_filters
# from .search_indexes import EventIndex
# from .search import bulk_indexing

from core.mixins import SearchBase
from coworker.events.models import Event


class SearchList(SearchBase, TemplateView):
    template_name = 'events/search_events.html'

    # def get(self, request, *args, **kwargs):
    #     return render(request, self.template_name, ctx)
    #
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['object_list'] = Event.objects.all()
        return ctx


class EventDetailView(DetailView):
    model = Event
    template_name = 'events/event_detail.html'
    slug_url_kwarg = "event"

    def get_context_data(self, **kwargs):
        return super(EventDetailView, self).get_context_data(**kwargs)



class AutocompleteBase:
    pass
from django.contrib.postgres.search import SearchVector

class AutocompleteEvent(AutocompleteBase, View):
    def get(self, request, *args, **kwargs):
        ctx = {}
        q = request.GET["q"]
        # from django.contrib.postgres.search import TrigramSimilarity
        # Event.objects.annotate(similarity=TrigramSimilarity('name', q)).filter(similarity__gt=0.3).order_by('-similarity')
        from .documents import EventDocument

        ss = EventDocument.search().query("match", description=q)
        qs = ss.to_queryset()
        # qs is just a django queryset and it is called with order_by to keep
        # the same order as the elasticsearch result.

        for event in ss:
            print(event.name, event.description)

        # ctx['q'] = list(Event.objects.filter(name__search=q).values_list("name", flat=True))
        # import pdb; pdb.set_trace()
        # return JsonResponse(ctx)
        return JsonResponse({"5162-coworkchm":{"value":"Cowork CHM, Hong Kong, Hong Kong","label":"Cowork CHM, Hong Kong, Hong Kong","loc":"3","idx":"5162","coworkspace_url":"hong-kong\/hong-kong\/cowork-chm"},"1807-coworkingspacebytheventures":{"value":"Coworking Space by TheVentures, Ho Chi Minh City, Vietnam","label":"Coworking Space by TheVentures, Ho Chi Minh City, Vietnam","loc":"3","idx":"1807","coworkspace_url":"vietnam\/ho-chi-minh-city\/coworking-space-by-theventures"},"2309-coworkinglegian":{"value":"Coworking Legian, Bali, Indonesia","label":"Coworking Legian, Bali, Indonesia","loc":"3","idx":"2309","coworkspace_url":"indonesia\/bali\/coworking-legian"},"1101-coworkzonehiteccity":{"value":"CoworkZone Hitec City, Hyderabad, India","label":"CoworkZone Hitec City, Hyderabad, India","loc":"3","idx":"1101","coworkspace_url":"india\/hyderabad\/coworkzone-hitec-city"},"4414-coworkinghub":{"value":"Coworking Hub, Hyderabad, India","label":"Coworking Hub, Hyderabad, India","loc":"3","idx":"4414","coworkspace_url":"india\/hyderabad\/coworking-hub"},"5274-coworking24":{"value":"CO-WORKING 24, Hyderabad, India","label":"CO-WORKING 24, Hyderabad, India","loc":"3","idx":"5274","coworkspace_url":"india\/hyderabad\/co-working-24"},"2088-coworkingurquiza":{"value":"Coworking Urquiza, Buenos Aires, Argentina","label":"Coworking Urquiza, Buenos Aires, Argentina","loc":"3","idx":"2088","coworkspace_url":"argentina\/buenos-aires\/coworking-urquiza"},"49-coworkingrosario":{"value":"Coworking Rosario, Rosario, Argentina","label":"Coworking Rosario, Rosario, Argentina","loc":"3","idx":"49","coworkspace_url":"argentina\/rosario\/coworking-rosario"},"v_s":{"value":"cowor","label":"<span>View All Results<\/span>","loc":0,"idx":0,"coworkspace_url":""}})

    def post(self, request, *args, **kwargs):
        return JsonResponse({"170-":{"value":"Moscow, Russia","label":"Moscow, Russia","loc":"2","idx":"170","coworkspace_url": "null"},"1489-cow":{"value":"Co.W, Salem, United States","label":"Co.W, Salem, United States","loc":"3","idx":"1489","coworkspace_url":"united-states\/oregon\/salem\/cow"},"5162-coworkchm":{"value":"Cowork CHM, Hong Kong, Hong Kong","label":"Cowork CHM, Hong Kong, Hong Kong","loc":"3","idx":"5162","coworkspace_url":"hong-kong\/hong-kong\/cowork-chm"},"1807-coworkingspacebytheventures":{"value":"Coworking Space by TheVentures, Ho Chi Minh City, Vietnam","label":"Coworking Space by TheVentures, Ho Chi Minh City, Vietnam","loc":"3","idx":"1807","coworkspace_url":"vietnam\/ho-chi-minh-city\/coworking-space-by-theventures"},"2309-coworkinglegian":{"value":"Coworking Legian, Bali, Indonesia","label":"Coworking Legian, Bali, Indonesia","loc":"3","idx":"2309","coworkspace_url":"indonesia\/bali\/coworking-legian"},"792-cowerkz":{"value":"CoWerkz, Singapore, Singapore","label":"CoWerkz, Singapore, Singapore","loc":"3","idx":"792","coworkspace_url":"singapore\/singapore\/cowerkz"},"1101-coworkzonehiteccity":{"value":"CoworkZone Hitec City, Hyderabad, India","label":"CoworkZone Hitec City, Hyderabad, India","loc":"3","idx":"1101","coworkspace_url":"india\/hyderabad\/coworkzone-hitec-city"},"4414-coworkinghub":{"value":"Coworking Hub, Hyderabad, India","label":"Coworking Hub, Hyderabad, India","loc":"3","idx":"4414","coworkspace_url":"india\/hyderabad\/coworking-hub"},"v_s":{"value":"cow","label":"<span>View All Results<\/span>","loc":0,"idx":0,"coworkspace_url":""}})

coworker/lab/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, TemplateView, CreateView, FormView
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, TemplateView, CreateView, FormView
from django.views import View
from .models import Entry
# Create your views here.
# aricles


class ArticleListView(View):
    template_name = "lab/lab_index.html"

    def get(self, request, *args, **kwargs):
        ctx = {}
        ctx['articles'] = Entry.objects.all()
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        #TODO figure out why and where called post method
        return self.get(request, *args, **kwargs)



class EntryDetail(DetailView):
    template_name = "lab/entry_detail.html"
    model = Entry
    context_object_name = "article"
# class ArticleListView(Views):
#     model = Entry
#     context_object_name = "articles"
#     template_name = "lab/lab_index.html"
#

coworker/search/views.py
from coworker.cities.models import City
from rest_framework import permissions
from rest_framework.decorators import api_view
from rest_framework.response import Response
from config.es_client import es_client
from rest_framework import views
from django import forms
from django.utils.translation import pgettext

from coworker.search.backends import get_search_backend
from coworker.place.models import Place

from rest_framework_elasticsearch import es_views, es_pagination, es_filters
from events.search_indexes import EventIndex
from place.documents import PlaceDocument
from search.serializers import PlaceSerializer, CitySerializer
from django.apps import apps

# @api_view(['GET', 'POST'])
class Autocomplete(views.APIView):
    search_key = "search"
    search_backend = 'default'

    def get_serializer(self):
        return self.get_model().get_serializer()

    def get_model(self):
        # return apps.get_model(self.kwargs['app'], self.kwargs['model'])
        return Place

    def get_queryset(self):

        return self.get_model().objects.all()

    def get(self, request, *args, **kwargs):
        backend = get_search_backend(self.search_backend)
        query = request.GET[self.search_key]
        results = backend.search(query, model_or_queryset=self.get_queryset())
        # {"792-cowerkz": {
        #     "value":"CoWerkz, Singapore, Singapore","label":"CoWerkz, Singapore, Singapore","loc":"3","idx":"792","coworkspace_url":"singapore\/singapore\/cowerkz"
        # }
        # }
        return Response(self.get_serializer()(results, many=True).data)

coworker/templates/users/registration.html
{% extends "responsive/base.html" %}
{% load sekizai_tags %}
{% load widget_tweaks %}
{% load i18n %}
{% load static %}
{% load bootstrap3 %}


{% block content %}
    <style>
        .btn-file {
            position: relative;
            overflow: hidden;
        }
        .btn-file input[type=file] {
            position: absolute;
            top: 0;
            right: 0;
            min-width: 100%;
            min-height: 100%;
            font-size: 100px;
            text-align: right;
            filter: alpha(opacity=0);
            opacity: 0;
            outline: none;
            background: white;
            cursor: inherit;
            display: block;
        }

        #img-upload{
            width: 100%;
        }
    </style>

    <div class="container">
        <form action='.' method="POST">
            {% csrf_token %}
            {% bootstrap_form_errors place_form %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <h3>{% trans 'Select Page Type' %}</h3>
                    <div class="form-group">
                        <label>{% trans "Profile image" %}</label>
                        <div class="input-group">
                            <span class="input-group-btn">
                                <span class="btn btn-default btn-file">
                                    {% trans "Browse…" %}{% render_field user_form.profile_image id="imgInp"  %}
                                </span>
                            </span>
                            <input type="text" class="form-control" readonly>
                        </div>
                        <img id='img-upload'/>
                    </div>

                    <div class="form-group">
                        <label class="control-label" >{{ user_form.user_type.label }}</label>
                        {% render_field user_form.user_type class="form-control" %}
                        {{ user_form.user_type.errors }}
                    </div>
                    <div class="form-group">
                        <label class="control-label" >{{ user_form.aboutme.label }}</label>
                        {% render_field user_form.aboutme class="form-control" %}
                        {{ user_form.aboutme.errors }}
                    </div>

                </div>


                <div class="col-md-4 col-md-offset-4 form-container hide" id="sp">
                     <div class="form-group">
                        <label class="control-label" >{{ place_form.space_name.label }}</label>
                        {% render_field place_form.space_name  class="form-control" %}
                        {{ place_form.space_name.errors }}
                    </div>

{#                    <div class="form-group">#}
{#                        <label class="control-label" >{{ place_form.city.label }}</label>#}
{#                        {% render_field place_form.city  class="form-control" %}#}
{#                        {{ place_form.city.errors }}#}
{#                    </div>#}
                    <div class="form-group">
                        <label class="control-label" >{{ place_form.address.label }}</label>
                        {% render_field place_form.address  class="form-control" %}
                        {{ place_form.address.errors }}
                    </div>
                    <div class="form-group">
                        <label class="control-label" >{{ place_form.lat_lng.label }}</label>
                        {#                         <input type="text" name="lat_lng" value="50.4501,30.523400000000038" required="" id="id_lat_lng" data-location-field-options="{&quot;map.provider&quot;: &quot;openstreetmap&quot;, &quot;map.zoom&quot;: 13, &quot;search.provider&quot;: &quot;google&quot;, &quot;search.suffix&quot;: &quot;&quot;, &quot;provider.google.api&quot;: &quot;//maps.google.com/maps/api/js&quot;, &quot;provider.google.api_key&quot;: &quot;AIzaSyDjNeEXP2tHApTTke_Oxz_1d--xfF-8fuY&quot;, &quot;provider.google.map_type&quot;: &quot;ROADMAP&quot;, &quot;provider.mapbox.access_token&quot;: &quot;&quot;, &quot;provider.mapbox.max_zoom&quot;: 18, &quot;provider.mapbox.id&quot;: &quot;mapbox.streets&quot;, &quot;provider.openstreetmap.max_zoom&quot;: 18, &quot;resources.root_path&quot;: &quot;/static/location_field&quot;, &quot;resources.media&quot;: {&quot;js&quot;: [&quot;/static/location_field/js/jquery.livequery.js&quot;, &quot;/static/location_field/js/form.js&quot;]}, &quot;field_options&quot;: {&quot;based_fields&quot;: [&quot;address&quot;], &quot;prefix&quot;: &quot;&quot;}}">#}
                        {% render_field place_form.lat_lng  class="form-control" %}
                         {{ place_form.lat_lng.errors }}
                    </div>

                    <div class="form-group">
                        <label class="control-label" >{{ place_form.cs_description.label }}</label>
                        {% render_field place_form.cs_description  class="form-control" %}
                        {{ place_form.cs_description.errors }}
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>

                </div>
            </div>
        </form>
    </div>



    {#     <div id="app">#}
    {#                <span v-bind:title="message">#}
    {#                    Hover your mouse over me for a few seconds#}
    {#                    to see my dynamically bound title!#}
    {#                  </span>#}
    {#            </div>#}
    {% addtoblock "js" %}
        <script>
          $(function () {
            $("#id_user_type").change(function() {
              var container_id = $(this).find("option:selected").attr('value');
              $(".form-container").addClass("hide");
              $("#"+container_id).toggleClass("hide");
            });
          });
        </script>
        <script src="https://unpkg.com/vue"></script>
        {#            <script>#}
        {#              $(function () {#}
        {#                var app = new Vue({#}
        {#                  el: '#app',#}
        {#                  data: {#}
        {#                    message: 'Hello Vue!'#}
        {#                  }#}
        {#                })#}
        {#              });#}
        {##}
        {#            </script>#}
        <script>

          $(document).ready( function() {
            $(document).on('change', '.btn-file :file', function() {
              var input = $(this),
                label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
              input.trigger('fileselect', [label]);
            });

            $('.btn-file :file').on('fileselect', function(event, label) {

              var input = $(this).parents('.input-group').find(':text'),
                log = label;

              if( input.length ) {
                input.val(log);
              } else {
                if( log ) alert(log);
              }

            });
            function readURL(input) {
              if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                  $('#img-upload').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
              }
            }

            $("#imgInp").change(function(){
              readURL(this);
            });
          });

        </script>



        <script src="{% static 'js/bundle.min.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js"></script>

        <script>
          $(function () {
            var places = L.featureGroup();
            document.map = L.map('map_lat_lng').setView([50.449, 30.5243], 10);
            L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
              maxZoom: 18,
              attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
              '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
              'Imagery © <a href="http://mapbox.com">Mapbox</a>',
              id: 'mapbox.streets'
            }).addTo(document.map);
            var marker = L.marker([50.449, 30.5243]);
            marker.addTo(places); // CAREFULL!!! The first position corresponds to the lat (y) and the second to the lon (x)
            marker.addTo(document.map);
            updateMarker($("#id_address"), marker, places);

            document.map.fitBounds(places.getBounds(), {maxZoom: 15});
            marker.dragging.enable();
            marker.on('drag', function(e) {
              console.log('marker drag event');
            });
            marker.on('dragend', function(e) {
              var position = marker.getLatLng();

              $('#id_lat_lng').val(position.lat + ',' + position.lng);
            });

            $("#id_address").change(function(e) {
              updateMarker(this, marker, places);
            });
          });
          function updateMarker(input, marker, places) {
            var query_addr = $(input).val();
            const provider = new window.GeoSearch.OpenStreetMapProvider();
            var query_promise = provider.search({ query: query_addr});

            query_promise.then( function(value) {
              for(i=0;i < value.length; i++){
                // Success!
                var x_coor = value[i].x;
                var y_coor = value[i].y;
                var label = value[i].label;
                // Create a marker for the found coordinates
                $('#id_lat_lng').val(y_coor + "," + x_coor);
                var newLatLng = new L.LatLng(y_coor, x_coor);
                marker.setLatLng(newLatLng);
                document.map.fitBounds(places.getBounds(), {maxZoom: 15})
                break;
              }
            }, function(reason){
              console.log(reason); // Error!
            });
          }
        </script>
        <script type="text/javascript" src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        <link href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" type="text/css" rel="stylesheet">
        <script type="text/javascript" src="/static/ajax_select/js/ajax_select.js"></script>


        <script>
          $(function() {
            $('#id_city_text').change(function() {
              console.log('ss');
              $(this).val($('#id_city_on_deck').html());
            });
          })
        </script>
    {% endaddtoblock %}
{% endblock %}

coworker/templates/users/reviews.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}


{% block title %}{% endblock %}

{% block content %}
    <h2>{% trans "Comment" %}</h2>

{% endblock content %}