config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.conf.urls.i18n import i18n_patterns
from ajax_select import urls as ajax_select_urls


#
# blog_urls = ([
#     url(r'^', include('zinnia.urls.capabilities')),
#     url(r'^search/', include('zinnia.urls.search')),
#     url(r'^sitemap/', include('zinnia.urls.sitemap')),
#     url(r'^trackback/', include('zinnia.urls.trackback')),
#     url(r'^blog/tags/', include('zinnia.urls.tags')),
#     url(r'^blog/feeds/', include('zinnia.urls.feeds')),
#     url(r'^blog/random/', include('zinnia.urls.random')),
#     url(r'^blog/authors/', include('zinnia.urls.authors')),
#     url(r'^blog/categories/', include('zinnia.urls.categories')),
#     url(r'^blog/comments/', include('zinnia.urls.comments')),
#     url(r'^blog/', include('zinnia.urls.entries')),
#     url(r'^blog/', include('zinnia.urls.archives')),
#     url(r'^blog/', include('zinnia.urls.shortlink')),
#     url(r'^blog/', include('zinnia.urls.quick_entry'))
# ], 'zinnia')
#



urlpatterns = i18n_patterns(
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # User management
    url(r'^select2/', include('django_select2.urls')),
    url(r'^ajax_select/', include(ajax_select_urls)),
    url(r'^', include('coworker.main.urls', namespace='main')),
    # url(r'^(?P<country>[\w-]+)/', include('coworker.place.urls', namespace='place')),
    url(r'^profile/', include('coworker.users.urls', namespace='users')),

    url(r'^accounts/', include('allauth.urls')),

    url(r'^places/', include('coworker.place.urls', namespace='place')),
    url(r'^events/', include('coworker.events.urls', namespace='events')),
    url(r'^services/', include('coworker.services.urls', namespace='services')),
    # url(r'^', include(blog_urls)),
    url(r'^lab/', include('coworker.lab.urls', namespace='lab')),
    url(r'^search/', include('coworker.search.urls', namespace='search')),
    url(r'^social/', include('coworker.social.urls', namespace='social')),


    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^comments/', include('django_comments.urls')),
    # Your stuff: custom urls includes go here


) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        url(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

coworker/lab/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^$', views.ArticleListView.as_view(), name='index'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        views.EntryDetail.as_view(),
        name='entry_detail'),
]

coworker/main/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^$', view=views.Index.as_view(), name='index'),
    url(r'^search/$', view=views.SearchView.as_view(), name='search'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^cities/$', TemplateView.as_view(template_name='pages/cities.html'), name='cities'),
    url(r'^team/$', TemplateView.as_view(template_name='pages/team.html'), name='team'),
    url(r'^contact/$', TemplateView.as_view(template_name='pages/contact.html'), name='contact'),
    url(r'^reviews/$', TemplateView.as_view(template_name='pages/reviews.html'), name='reviews'),
    url(r'^terms/$', TemplateView.as_view(template_name='pages/terms.html'), name='terms'),
    url(r'^privacy-policy/$', TemplateView.as_view(template_name='pages/privacy-policy.html'), name='privacy-policy'),
    url(r'^help/$', TemplateView.as_view(template_name='pages/help.html'), name='help'),
]

coworker/place/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^card/api/(?P<pk>\d+)/$', view=views.PlaceDetailApiView.as_view(), name='detail_card'),
    url(r'^map/api/$', view=views.PlaceMapApiView.as_view(), name='map_api'),


    #url(r'^list-space/success/$', view=views.PlaceAddSuccess.as_view(), name='list-space-success'),


    #photo edit urls


    url(r'^search/autocomplete/$', views.autocomplete),

    url(r'^search/$', view=views.SearchList.as_view(), name='search'),
    url(r'^search/(?P<country>[\w-]+)/', view=views.SearchList.as_view(), name='search-country'), #HERE REMOVED $


    url(r'^(?P<country>[\w-]+)/$', view=views.PlaceCountryList.as_view(), name='country'),
    url(r'^(?P<country>[\w-]+)/(?P<city>[\w-]+)/$', view=views.PlaceCityList.as_view(), name='city'),
    url(r'^(?P<country>[\w-]+)/(?P<city>[\w-]+)/(?P<place>[\w-]+)/$',
        view=views.PlaceView.as_view(), name='place'),
    # url(r'^(?P<city>[\w-]+)/(?P<place>.*)/$', view=views.Place.as_view(), name='place'),


]

coworker/main/models.py
from django.db import models

coworker/search/models.py
from django.db import models

# Create your models here.

coworker/social/models.py
from django.db import models
from django.utils import timezone

from coworker.users.models import User


class Tweet(models.Model):
    user = models.ForeignKey(User, related_name='tweets')
    created = models.DateTimeField(default=timezone.now)
    body = models.TextField()

coworker/social/forms.py
from .models import Tweet
from django import forms


class TweetForm(forms.ModelForm):

    class Meta:
        model = Tweet
        fields = ['body']

coworker/events/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DetailView, ListView, TemplateView
from django.views.decorators.csrf import csrf_exempt
from rest_framework.response import Response

from config.es_client import es_client

from rest_framework_elasticsearch import es_views, es_pagination, es_filters
# from .search_indexes import EventIndex
# from .search import bulk_indexing

from core.mixins import SearchBase
from coworker.events.models import Event


class SearchList(SearchBase, TemplateView):
    template_name = 'events/search_events.html'

    # def get(self, request, *args, **kwargs):
    #     return render(request, self.template_name, ctx)
    #
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['object_list'] = Event.objects.all()
        return ctx


class EventDetailView(DetailView):
    model = Event
    template_name = 'events/event_detail.html'
    slug_url_kwarg = "event"

    def get_context_data(self, **kwargs):
        return super(EventDetailView, self).get_context_data(**kwargs)



class AutocompleteBase:
    pass
from django.contrib.postgres.search import SearchVector

class AutocompleteEvent(AutocompleteBase, View):
    def get(self, request, *args, **kwargs):
        ctx = {}
        q = request.GET["q"]
        # from django.contrib.postgres.search import TrigramSimilarity
        # Event.objects.annotate(similarity=TrigramSimilarity('name', q)).filter(similarity__gt=0.3).order_by('-similarity')
        from .documents import EventDocument

        ss = EventDocument.search().query("match", description=q)
        qs = ss.to_queryset()
        # qs is just a django queryset and it is called with order_by to keep
        # the same order as the elasticsearch result.

        for event in ss:
            print(event.name, event.description)

        # ctx['q'] = list(Event.objects.filter(name__search=q).values_list("name", flat=True))
        # import pdb; pdb.set_trace()
        # return JsonResponse(ctx)
        return JsonResponse({"5162-coworkchm":{"value":"Cowork CHM, Hong Kong, Hong Kong","label":"Cowork CHM, Hong Kong, Hong Kong","loc":"3","idx":"5162","coworkspace_url":"hong-kong\/hong-kong\/cowork-chm"},"1807-coworkingspacebytheventures":{"value":"Coworking Space by TheVentures, Ho Chi Minh City, Vietnam","label":"Coworking Space by TheVentures, Ho Chi Minh City, Vietnam","loc":"3","idx":"1807","coworkspace_url":"vietnam\/ho-chi-minh-city\/coworking-space-by-theventures"},"2309-coworkinglegian":{"value":"Coworking Legian, Bali, Indonesia","label":"Coworking Legian, Bali, Indonesia","loc":"3","idx":"2309","coworkspace_url":"indonesia\/bali\/coworking-legian"},"1101-coworkzonehiteccity":{"value":"CoworkZone Hitec City, Hyderabad, India","label":"CoworkZone Hitec City, Hyderabad, India","loc":"3","idx":"1101","coworkspace_url":"india\/hyderabad\/coworkzone-hitec-city"},"4414-coworkinghub":{"value":"Coworking Hub, Hyderabad, India","label":"Coworking Hub, Hyderabad, India","loc":"3","idx":"4414","coworkspace_url":"india\/hyderabad\/coworking-hub"},"5274-coworking24":{"value":"CO-WORKING 24, Hyderabad, India","label":"CO-WORKING 24, Hyderabad, India","loc":"3","idx":"5274","coworkspace_url":"india\/hyderabad\/co-working-24"},"2088-coworkingurquiza":{"value":"Coworking Urquiza, Buenos Aires, Argentina","label":"Coworking Urquiza, Buenos Aires, Argentina","loc":"3","idx":"2088","coworkspace_url":"argentina\/buenos-aires\/coworking-urquiza"},"49-coworkingrosario":{"value":"Coworking Rosario, Rosario, Argentina","label":"Coworking Rosario, Rosario, Argentina","loc":"3","idx":"49","coworkspace_url":"argentina\/rosario\/coworking-rosario"},"v_s":{"value":"cowor","label":"<span>View All Results<\/span>","loc":0,"idx":0,"coworkspace_url":""}})

    def post(self, request, *args, **kwargs):
        return JsonResponse({"170-":{"value":"Moscow, Russia","label":"Moscow, Russia","loc":"2","idx":"170","coworkspace_url": "null"},"1489-cow":{"value":"Co.W, Salem, United States","label":"Co.W, Salem, United States","loc":"3","idx":"1489","coworkspace_url":"united-states\/oregon\/salem\/cow"},"5162-coworkchm":{"value":"Cowork CHM, Hong Kong, Hong Kong","label":"Cowork CHM, Hong Kong, Hong Kong","loc":"3","idx":"5162","coworkspace_url":"hong-kong\/hong-kong\/cowork-chm"},"1807-coworkingspacebytheventures":{"value":"Coworking Space by TheVentures, Ho Chi Minh City, Vietnam","label":"Coworking Space by TheVentures, Ho Chi Minh City, Vietnam","loc":"3","idx":"1807","coworkspace_url":"vietnam\/ho-chi-minh-city\/coworking-space-by-theventures"},"2309-coworkinglegian":{"value":"Coworking Legian, Bali, Indonesia","label":"Coworking Legian, Bali, Indonesia","loc":"3","idx":"2309","coworkspace_url":"indonesia\/bali\/coworking-legian"},"792-cowerkz":{"value":"CoWerkz, Singapore, Singapore","label":"CoWerkz, Singapore, Singapore","loc":"3","idx":"792","coworkspace_url":"singapore\/singapore\/cowerkz"},"1101-coworkzonehiteccity":{"value":"CoworkZone Hitec City, Hyderabad, India","label":"CoworkZone Hitec City, Hyderabad, India","loc":"3","idx":"1101","coworkspace_url":"india\/hyderabad\/coworkzone-hitec-city"},"4414-coworkinghub":{"value":"Coworking Hub, Hyderabad, India","label":"Coworking Hub, Hyderabad, India","loc":"3","idx":"4414","coworkspace_url":"india\/hyderabad\/coworking-hub"},"v_s":{"value":"cow","label":"<span>View All Results<\/span>","loc":0,"idx":0,"coworkspace_url":""}})

coworker/lab/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, TemplateView, CreateView, FormView
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, TemplateView, CreateView, FormView
from django.views import View
from .models import Entry
# Create your views here.
# aricles


class ArticleListView(View):
    template_name = "lab/lab_index.html"

    def get(self, request, *args, **kwargs):
        ctx = {}
        ctx['articles'] = Entry.objects.all()
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        #TODO figure out why and where called post method
        return self.get(request, *args, **kwargs)



class EntryDetail(DetailView):
    template_name = "lab/entry_detail.html"
    model = Entry
    context_object_name = "article"
# class ArticleListView(Views):
#     model = Entry
#     context_object_name = "articles"
#     template_name = "lab/lab_index.html"
#

coworker/main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView
from coworker.place.models import Place, Category
from coworker.services.models import Category as ServiceCategory, Service
from coworker.users.models import User



class Index(TemplateView):
    template_name = 'responsive/index.html'

    def get_context_data(self, **kwargs):
        # places_tmp = Place.objects.order_by('?').all()[:8]
        # d = {}
        # for i, p in enumerate(places_tmp):
        #     d["place_%s" % (i+1)] = p
        # ctx = {
        #     "places": Place.objects.order_by('?').all()[:10],
        # }
        # ctx['place_category'] = list(Category.objects.values_list('name', flat=True))
        # ctx['service_categories'] = list(ServiceCategory.objects.values_list('name', flat=True))
        # event_category = Category.objects.all()
        # search_category = Category.objects.all()
        ctx = {}
        return ctx

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('main:search'))
        return super().get(request, *args, **kwargs)


from coworker.search.backends import get_search_backend


class SearchView(View):
    template_name = 'responsive/places.html'
    # template_name = 'pages/map_tab.html'
    search_key = "q"
    search_backend = 'default'

    def get(self, request, *args, **kwargs):
        ctx = {}
        q = request.GET.get(self.search_key)
        ctx['q'] = q if q != 'None' else ''
        page = request.GET.get("f", "map")

        if page == "map":
            self.template_name = 'responsive/map_tab.html'
        elif page in ["places", "top", "latest"]:
            backend = get_search_backend(self.search_backend)
            places = Place.objects.all()
            if q:
                places = backend.search(q, model_or_queryset=places)
            else:
                places = Place.objects.order_by("?")[:10]
            ctx["object_list"] = places
        elif page == "investors":
            ctx["object_list"] = User.objects.filter(user_type=User.INVESTORS)

        return render(request, self.template_name, ctx)

coworker/search/views.py
from coworker.cities.models import City
from rest_framework import permissions
from rest_framework.decorators import api_view
from rest_framework.response import Response
from config.es_client import es_client
from rest_framework import views
from django import forms
from django.utils.translation import pgettext

from coworker.search.backends import get_search_backend
from coworker.place.models import Place

from rest_framework_elasticsearch import es_views, es_pagination, es_filters
from events.search_indexes import EventIndex
from place.documents import PlaceDocument
from search.serializers import PlaceSerializer, CitySerializer
from django.apps import apps

# @api_view(['GET', 'POST'])
class Autocomplete(views.APIView):
    search_key = "search"
    search_backend = 'default'

    def get_serializer(self):
        return self.get_model().get_serializer()

    def get_model(self):
        # return apps.get_model(self.kwargs['app'], self.kwargs['model'])
        return Place

    def get_queryset(self):

        return self.get_model().objects.all()

    def get(self, request, *args, **kwargs):
        backend = get_search_backend(self.search_backend)
        query = request.GET[self.search_key]
        results = backend.search(query, model_or_queryset=self.get_queryset())
        # {"792-cowerkz": {
        #     "value":"CoWerkz, Singapore, Singapore","label":"CoWerkz, Singapore, Singapore","loc":"3","idx":"792","coworkspace_url":"singapore\/singapore\/cowerkz"
        # }
        # }
        return Response(self.get_serializer()(results, many=True).data)

coworker/templates/pages/help.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}


{% block title %}{% trans "Coworker ­- cowork spaces for coworking people" %}{% endblock %}


{% block content %}
    <section class="faq_banner_outer">
        <div class="container">
            <div class="row">
                <div class=" col-xs-12 pade_none faq_banner_inner"><img src="{% static 'img/img_faq_banner_pic.png' %}" alt="">
                </div>
            </div>
        </div>
    </section>
    <!--BANNER END-->

    <!--FAQ CONTENT PART START-->
    <section class="faq_content_main">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 pade_none coworker_com_outer">
                    <div class="open_faq_pic"><img src="{% static 'img/img_open_pic.png' %}" alt=""></div>
                    <div class="coworker_com_left box_styling">
                        <h3>{% trans "What can SpacesMap do？" %}</h3>
                        <p>{% trans "We hit off the cloud site in the great bridge between people. Youcan search according to the state, city and site name. You can alsoselect according to different conditions, such as the price, thismonth score. " %}</p>
                        <div class="com_bottom_arrow"><img src="{% static 'img/img_faq_bottom_arrow.png' %}" alt=""></div>
                    </div>
                </div>

                <div class="col-xs-12 pade_none add_coworker_space_panel">
                    <div class="staright_dottedline"><img src="{% static 'img/img_faq_dottedline.png' %}" alt=""></div>
                    <div class="add_collecting_outer box_styling">
                        <h3>{% trans "Who can add the site of the SpacesMap?" %}</h3>
                        <p>{% trans "Anyone can add a site hit off the SpcaeMap! But we need to fill outa lot of information (area, which can accommodate the number, costand so on), we suggested by official representatives to add thesite, these official representative is usually business owners,administrators and cloud site team members. " %}</p>
                        <div class="collecting_bottom_arrow"><img src="{% static 'img/img_faq_bottom_arrow(1).png' %}" alt=""></div>
                    </div>

                    <div class="col-xs-12 pade_none">
                        <div class="mold_dottedline"><img src="{% static 'img/img_dottedline_mold.png' %}" alt=""></div>
                        <div class="faq_glad_outer box_styling">
                            <div class="glad_top_arrow"><img src="{% static 'img/img_faq_top_arrow.png' %}" alt=""></div>
                            <h3>{% trans "How can i add the site of the SpacesMap?" %}</h3>
                            <p>{% trans "I'm glad you asked this question!" %}" <a href="{% url "place:list-space" %}">{% trans "Click" %}</a> {% trans "Adding SpacesMap" %}</p>
                        </div>

                        <div class="faq_countries_outer box_styling02">
                            <div class="countries_left_arrow"><img src="{% static 'img/img_faq_left_arrow.png' %}" alt=""></div>
                            <h3>{% trans "What cities do we support?" %}</h3>
                            <p>{% trans "Most domestic cities have SpacesMap sites, and every day there are new cities to join SpacesMap." %}</p>
                        </div>
                    </div>

                </div>


                <div class="col-xs-12 pade_none cost_faq_outer_con">
                    <div class="col-sm-7 col-md-7 col-xs-12 pade_none">
                        <div class="faq_cost_con box_styling">
                            <div class="cost_right_arrow"><img src="{% static 'img/img_faq_right_arrow.png' %}" alt=""></div>
                            <h3>{% trans "How much to pay the charge？" %}</h3>
                            <p>{% trans "No charge!" %}</p>
                        </div>

                        <div class="faq_submit_con box_styling">
                            <div class="submit_right_arrow"><img src="{% static 'img/img_faq_right_arrow.png' %}" alt=""></div>
                            <h3>{% trans "I submitted the site request, and then?" %}</h3>
                            <p>{% trans "当您填写完”出租场地“表格并点击”提交“按钮后，这份表格会传递到审核部。我们会对您的填写内容编辑（如果有拼写或语法错误的话）。当您的场地添加成功时，您会收到我们发送给您的一封邮件。" %}</p>
                        </div>

                    </div>


                    <div class="col-sm-5 col-md-5 col-xs-12 pade_none">
                        <div class="faq_listing_con box_styling">
                            <div class="listing_right_arrow"><img src="{% static 'img/img_faq_top_arrow.png' %}" alt=""></div>
                            <h3>{% trans "How do I edit my creating cloud site list?" %}</h3>
                            <p>{% trans "如果您已经提交场地信息，请登录您的账号，点击"我的创客云图场地"按钮。如果工作人员添加了您的场地，请直接给spaces@spacesmap.com发送一封邮件，我们会授予您管理权限。" %}</p>
                        </div>
                    </div>

                </div>

                <div class="free_service_faq_outer box_styling">
                    <div class="free_service_top_arrow"><img src="{% static 'img/img_faq_left_arrow.png' %}" alt=""></div>
                    <h3>{% trans "I can find a free beer hit off the cloud site?" %}</h3>
                    <p>{% trans "Of course！ Pass!" %}" <a href="{% url "place:search" %}">{% trans "Further screening" %}</a> {% trans "You can choose the site (free beer, vertical desk, monitor, eventrampoline, etc.) according to all kinds of conditions." %}</p>
                </div>

            </div>


            <div class="col-xs-12 pade_none edit_faq_outer_con">
                <div class="got_another_faq_outer box_styling">
                    <div class="got_top_arrow"><img src="{% static 'img/img_faq_top_arrow.png' %}" alt=""></div>
                    <h3>{% trans "Any other questions?" %}</h3>
                    <p>{% trans "Please send mail to..." %}" <a href="mailto:hello@coworker.com">hello@spacesmap.com</a></p>
                </div>
            </div>
        </div>
    </section>
    <!--FAQ CONTENT PART END-->

{% endblock content %}

coworker/templates/pages/index.html
{#{% extends 'base2.html' %}#}
{% extends 'base.html' %}

coworker/templates/pages/map_tab.html
{% extends 'pages/inner_main.html' %}
{% load i18n %}
{% load static %}
{% load sekizai_tags %}

{% block body_css %} no-nav-banners three-col logged-in user-style-comalex3 AdaptiveSearchPage AdaptiveDefaultPage supports-drag-and-drop {% endblock %}

{% block inner_content %}

    <style>
        .leaflet-popup-content-wrapper {
            background: none;
        {#            color: transparent;#}
            box-shadow: none;
        }
        .leaflet-container a.leaflet-popup-close-button {
            top: 18px;
            right: 18px;
        }
        .leaflet-popup-tip-container { bottom: -20px; };

    </style>
    <div class="Grid-cell u-size2of3 u-lg-size3of4">
        <div id="map_canvas" style="height: 777px; position: relative; overflow: hidden;"></div>

        <div style="display: none">
            <div id="profile-hover-container" data-screen-name="HowdyAI" data-user-id="3450748273" style="opacity: 1; "></div>
        </div>

        <script id="popup_template" type="text/html">
            {% include "pages/popup_template.html" %}
        </script>


        <script>
          var places = L.featureGroup();
          document.map = L.map('map_canvas').setView([50.449, 30.5243], 10);
          L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
            maxZoom: 18,
            attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
            '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
            'Imagery © <a href="http://mapbox.com">Mapbox</a>',
            id: 'mapbox.streets'
          }).addTo(document.map);
          var popup_template = $('#popup_template');

          $.get("{% url 'place:map_api' %}?q={{ q }}", function(data) {
            $.each(data, function(i, v) {
              var marker = L.marker([v.lat, v.lng]);
              marker.addTo(document.map);
              marker.bindPopup("Loading...");
              marker.addTo(places);

              marker.on('mouseover', function (e) {
                var popup = e.target.getPopup();
                var self = this;
                $.get('/places/card/api/'+ v.pk, function(data) {
                  $("#profile-hover-container").html(data);
                  popup.setContent($("#profile-hover-container").html());
                  popup.update();
                  self.openPopup();
                });
              });
              document.map.fitBounds(places.getBounds(), {maxZoom: 15})
            });
          });

        </script>
    </div>
{% endblock %}